sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexanderlaudino/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexanderlaudino/docker-react npm run test