sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alexanderlaudino/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexanderlaudino/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-169333045166"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"